SELECT * 
FROM VATTU 
ORDER BY TenVTu DESC

SELECT TenNhaCc
FROM NHACC
WHERE DiaChi = N'1 TP HO CHI MINH'
ORDER BY TenNhaCc ASC

SELECT *, SlNhap*DgNhap AS 'THANH TIEN'
FROM CTPNHAP

SELECT DISTINCT NCC.MaNhaCc, NCC.TenNhaCc
FROM NHACC AS NCC JOIN DONDH AS DH
	ON  NCC.MaNhaCc = DH.MaNhaCc

SELECT *
FROM DONDH
WHERE NgayDh = (SELECT MAX(NgayDh) FROM DONDH)

SELECT SoPx, SlXuat*DgXuat AS 'TONG GIA TRI' 
FROM CTPXUAT
ORDER BY SlXuat*DgXuat DESC

SELECT VT.TenVTu, COUNT(CTPX.SlXuat)  
FROM VATTU AS VT JOIN CTPXUAT AS CTPX
	ON VT.MaVTu = CTPX.MaVTu
GROUP BY VT.TenVTu

DELETE CTDONDH
FROM CTDONDH AS CTDH JOIN DONDH AS DH
	ON CTDH.SoDh = DH.SoDh
WHERE DH.NgayDh = 2002/01/15

DELETE CTPXUAT
FROM CTPXUAT

INSERT INTO CTDONDH VALUES
('D001', 'DD01', 10),
('D001', 'DD02', 15),
('D002', 'VD02', 30),
('D003', 'TV14', 10),
('D003', 'TV29', 20),
('D004', 'TV14', 10),
('D002', 'TV14', 10),
('D001', 'VD01', 20);

SELECT CTPN.SoPn, PN.NgayNhap
FROM CTPNHAP AS CTPN JOIN PNHAP AS PN
	ON CTPN.SoPn = PN.SoPn
UNION 
SELECT VT.TenVTu, CTPN.SlNhap
FROM CTPNHAP AS CTPN JOIN VATTU AS VT
	ON CTPN.MaVTu = VT.MaVTu

SELECT *, SlXuat*DgXuat AS 'THANH TIEN'
FROM CTPXUAT AS CTPX JOIN PXUAT AS PX
COMPUTE 